name: Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  Ejercicio:
    runs-on: ubuntu-latest

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v3

      - uses: docker://gcr.io/hdl-containers/sim/osvb
        with:
          args: ./Ejercicio/VUnit/vunit_run.py
