name: Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:


  Ejercicio:
    runs-on: ubuntu-latest

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/hdl/sim/osvb:latest
        with:
          args: ./Ejercicio/vunit_run.py


  Proyecto:
    runs-on: ubuntu-latest

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/hdl/sim:latest
        with:
          args: ./Proyecto/run.sh


  Extra:
    runs-on: ubuntu-latest

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/hdl/impl/icestorm:latest
        with:
          args: ./Extra/run.sh

      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: Extra
          path: |
            ./Extra/top.asc
            ./Extra/top.json
            ./Extra/top.bin

  MiWi:
    runs-on: ubuntu-latest

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/hdl/impl/icestorm:latest
        with:
          args: ./MiWi/make.sh

      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: MiWi
          path: ./top_MiWi.bin

